version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: homebudget-postgres
    environment:
      POSTGRES_USER: homebudget
      POSTGRES_PASSWORD: homebudget123
      POSTGRES_DB: homebudget
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homebudget"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  homebudget-network:
    driver: bridge